In [4]:
import numpy as np
import math

In [5]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.shape

(2, 3)

The first number represents how many internal lists we have and second number represents how many members these internal list have

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(b)
b[0,0],b[0,1],b[1,0]

[[1 2 3]
 [4 5 6]]


(1, 2, 4)

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.full((2,2),math.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [12]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [13]:
np.full((3,2),4, dtype=int)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.random((4,3))

array([[0.84886813, 0.21827142, 0.31980045],
       [0.43841456, 0.86876629, 0.00429956],
       [0.03885029, 0.36614126, 0.47824962],
       [0.85823949, 0.7847274 , 0.19832172]])

single random number can also be generated

In [16]:
np.random.random()

0.6345067115870054

Dependence of subset of an array
Any changes made in the subset of numpy array ,
they reflect in parent array.It is always good to use 
function copy to make an independent array.


In [17]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[:2,1:3]
print("The array b is\n",b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The array b is
 [[2 3]
 [6 7]]


In [18]:
c=a[:2,1:3].copy()
print('This is C :\n',c )
      

This is C :
 [[2 3]
 [6 7]]


c is independent of a

In [19]:
b[0,1]=77
print(b)

[[ 2 77]
 [ 6  7]]


In [20]:
print(a)

[[ 1  2 77  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(a[0,2])
print(c[0,1])

77
3


In [22]:
c[0,1]=99
print(a)
print(c)

[[ 1  2 77  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2 99]
 [ 6  7]]


conditional access of arrays


In [23]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
c=a>2
c

array([[False, False],
       [ True,  True],
       [ True,  True]])

we can use these comparision expressions directly for access.
Result is only those elements for which the expression evaluates to True


In [25]:
print(a[c])
print(a[c].shape)

[3 4 5 6]
(4,)


Multiple coditions can also be evaluated

In [26]:
#a[(a>2)|(a<5)]
a[(a>2)&(a<5)]

array([3, 4])

Array operations

In [27]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [28]:
x


array([[1, 2],
       [3, 4]])

In [29]:
y

array([[5, 6],
       [7, 8]])

In [30]:
x+y

array([[ 6,  8],
       [10, 12]])

In [31]:
np.add(x,y)
#print(x+y)

array([[ 6,  8],
       [10, 12]])

In [32]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [33]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

element wise multiplication

In [34]:
print(x*y)

[[ 5 12]
 [21 32]]


In [35]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [36]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [37]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [38]:
v=np.array([9,10])
v

array([ 9, 10])

In [39]:
w=np.array([11,12])
w

array([11, 12])

In [40]:
v.dot(w)

219

In [41]:
np.dot(v,w)

219

In [42]:
print(v.shape)
print(w.shape)

(2,)
(2,)


In [43]:
#we can manually reshape 2X1 matrices

In [44]:
v=v.reshape((1,2))
w=w.reshape((1,2))

In [45]:
print(v.shape)
print(w.shape)

(1, 2)
(1, 2)


In [46]:
print(v)
print('v transpose is:',v.T)
print(w)
print('w transpose is:',w.T)

[[ 9 10]]
v transpose is: [[ 9]
 [10]]
[[11 12]]
w transpose is: [[11]
 [12]]


other Functions

In [47]:
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
np.sum(x)

21


using axis option in function sum we can sum across both the dimension of array


In [49]:
np.sum(x,axis=0)

array([ 9, 12])

In [50]:
np.sum(x,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [51]:
x.T


array([[1, 3, 5],
       [2, 4, 6]])

In [52]:
x=np.array([[1,2,3],[4,5,6,],[7,8,9],[10,11,12]])
y=np.array([2,1,3])


In [53]:
yy=np.tile(y,(4,1))
yy


array([[2, 1, 3],
       [2, 1, 3],
       [2, 1, 3],
       [2, 1, 3]])

In [54]:
print(x+yy)

[[ 3  3  6]
 [ 6  6  9]
 [ 9  9 12]
 [12 12 15]]


In [55]:
print(x+y)

[[ 3  3  6]
 [ 6  6  9]
 [ 9  9 12]
 [12 12 15]]


In [56]:
np.linspace(start=2,stop=10,num=15)

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

here argument num essentially represent number of elements in sequence , elements in sequence are natuarlly equally spaced 

we can also create new arrays by randomly sampling an original array, or simply creating an array with random numbers using random package within numpy

In [57]:
np.random.randint(high=25,low=1,size=(2,3))

array([[11, 13, 24],
       [16, 24,  5]])

In [58]:
np.random.randint(high=10,low=1,size=(3,2))

array([[9, 6],
       [7, 9],
       [4, 6]])

In [59]:
np.random.random(size=(3,4))

array([[0.63617384, 0.49764917, 0.24574252, 0.1947745 ],
       [0.28545095, 0.0351803 , 0.77336853, 0.8983145 ],
       [0.53728542, 0.97210557, 0.68237205, 0.44085075]])

In [60]:
y=np.random.choice(['a','b'],6)
print(y)

['b' 'a' 'b' 'a' 'a' 'a']


In [61]:
y=np.random.choice(['a','b'],1000)
#print(y)
y

array(['b', 'b', 'a', 'a', 'a', 'b', 'a', 'b', 'b', 'b', 'b', 'b', 'b',
       'b', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a',
       'b', 'b', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'a', 'b',
       'a', 'b', 'b', 'b', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'b', 'b',
       'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'b',
       'a', 'b', 'a', 'a', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'a', 'b',
       'a', 'b', 'a', 'b', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'a',
       'b', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'b',
       'a', 'b', 'b', 'b', 'a', 'b', 'a', 'a', 'b', 'b', 'b', 'b', 'b',
       'b', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'b', 'a', 'a', 'b', 'a',
       'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'b',
       'b', 'b', 'b', 'a', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'a',
       'b', 'a', 'b', 'b', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'a',
       'b', 'b', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'a', 'b', 'b

In [62]:
np.unique(y,return_counts=True)

(array(['a', 'b'], dtype='<U1'), array([493, 507], dtype=int64))

by default here both a and b get picked with almost equal probability in the random sample. Although this doesnt mean that individual values are not random , but overall percentage of a and b remains almost same. We can force approx probability structure by using option p

In [ ]:
y=np.random.choice(['a','b'],1000,p=[0.8,0.2])

In [ ]:
np.unique(y,return_counts=True)

In [ ]:
x=np.random.randint(high=100,low=2,size=(15,))
x

sorting 2-D arrays

In [ ]:
#x.sort()
print(x.sort)

In [ ]:
x=np.random.randint(high=100,low=12,size=(2,3))
x

In [ ]:
x.sort()
x

In [ ]:
x=np.random.randint(high=10,low=1,size=(15,))

In [ ]:
print(x)
x.max()

In [ ]:
x.argmax()